[project]
name = 'Decentralized-Energy-Dark-Matter-Research'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.data-sharing-protocol]
path = 'contracts/data-sharing-protocol.clar'
clarity_version = 2
epoch = 2.5

[contracts.discovery-tracking]
path = 'contracts/discovery-tracking.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
